pc1[0]="A"
pc1[image]="kathara/damper"

pc2[0]="A"
pc2[image]="kathara/damper"

gw[0]="A"
gw[1]="B"
gw[sysctl]="net.ipv4.ip_forward=1"
gw[image]="kathara/damper"

ext[0]="B"
ext[image]="kathara/base"
